# Generated by Django 5.2.11 on 2026-09-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='El nombre con que el programa lo pide. No se cambia.', max_length=80, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(help_text='Lo que se muestra o se usa. Esto es lo que se cambia.', verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número')], default='texto', max_length=10)),
                ('para_que', models.CharField(help_text='Dónde se ve y qué pasa si se cambia.', max_length=300, verbose_name='Para qué sirve')),
                ('de_fabrica', models.TextField(blank=True, help_text='Con lo que vino. Sirve para volver atrás.', verbose_name='Valor de fábrica')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes de la plataforma',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='EtapaDelCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(help_text='El del ciclo, de planear a mantener. No es alfabético a propósito: el orden enseña por dónde va un proyecto.', verbose_name='Orden')),
                ('carpeta', models.CharField(help_text='Dentro de `cvds/`. Con esto se reconocen sus documentos: cambiarla hace que dejen de encontrarse.', max_length=60, unique=True, verbose_name='Carpeta')),
                ('nombre', models.CharField(help_text='Como se lee en la pantalla. «Planear», no «planificacion».', max_length=60, verbose_name='Nombre en claro')),
                ('pregunta', models.CharField(max_length=200, verbose_name='Qué se responde en esta etapa')),
                ('queda', models.CharField(max_length=300, verbose_name='Qué queda escrito en ella')),
            ],
            options={
                'verbose_name': 'Etapa del ciclo',
                'verbose_name_plural': 'Etapas del ciclo de vida',
                'ordering': ['orden'],
            },
        ),
    ]
