# Generated by Django 5.2.17 on 2026-10-06 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_tres_capas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(help_text='base/01-conducta.md', max_length=255, unique=True)),
                ('contenido', models.TextField(blank=True, default='')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ruta'],
            },
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='como el archivo: aprobar-antes-de-commit.md', max_length=200)),
                ('contenido', models.TextField(blank=True, default='')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recuerdos', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['proyecto', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'nombre'), name='un_recuerdo_por_nombre')],
            },
        ),
    ]
