# Generated by Django 5.2.17 on 2026-10-06 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0001_initial'),
        ('proyectos', '0004_tres_capas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(choices=[('documento', 'Documento del estándar'), ('recuerdo', 'Recuerdo de un proyecto')], max_length=10)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('cambiar', 'Cambiar'), ('quitar', 'Quitar')], max_length=10)),
                ('ruta', models.CharField(blank=True, default='', help_text='del documento: base/…', max_length=255)),
                ('nombre', models.CharField(blank=True, default='', help_text='del recuerdo', max_length=200)),
                ('contenido', models.TextField(blank=True, default='', help_text='el texto completo que queda')),
                ('motivo', models.TextField(blank=True, default='')),
                ('quien', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('resuelta', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='proyectos.proyecto')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
