# Generated by Django 5.2.17 on 2026-10-07 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0002_propuesta'),
        ('historia', '0002_version'),
        ('proyectos', '0004_tres_capas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, default='')),
                ('regla', models.CharField(blank=True, default='', help_text='la regla que toca, como 02·F8', max_length=20)),
                ('quien', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('corregido', 'Corregido'), ('descartado', 'Descartado')], default='abierto', max_length=10)),
                ('motivo', models.TextField(blank=True, default='', help_text='por qué se descartó')),
                ('resuelto', models.DateTimeField(blank=True, null=True)),
                ('avisado', models.BooleanField(default=False, help_text='el proyecto ya se enteró de cómo quedó')),
                ('corregido_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_corregidos', to='historia.version')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='proyectos.proyecto')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
