# Generated by Django 5.2.17 on 2026-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
