# Generated by Django 5.2.17 on 2026-10-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0004_motivo_rechazo'),
        ('proyectos', '0006_sin_opt_in_17'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='02-flujo-de-trabajo', max_length=80, unique=True)),
                ('numero', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=200)),
                ('prefijo', models.CharField(blank=True, default='', help_text='F, DOC…', max_length=10)),
                ('documento', models.ForeignKey(blank=True, help_text='el documento que abre el capítulo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitulos', to='estandar.documento')),
            ],
            options={
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='su lugar dentro del documento')),
                ('codigo', models.CharField(help_text='F8, DOC22…; no cambia nunca (20·M4)', max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('marca', models.CharField(blank=True, choices=[('', 'Sin marca'), ('blindada', 'Blindada'), ('opt-in', 'Opt-in'), ('derogada', 'Derogada')], default='', max_length=10)),
                ('marca_texto', models.CharField(blank=True, default='', help_text='como se escribe la marca al final del título', max_length=160)),
                ('exigencia', models.TextField()),
                ('excepcion', models.TextField(blank=True, default='')),
                ('excepcion_condicion', models.TextField(blank=True, default='')),
                ('excepcion_limite', models.TextField(blank=True, default='')),
                ('excepcion_autoriza', models.TextField(blank=True, default='')),
                ('ejemplo', models.TextField(blank=True, default='')),
                ('ejemplo_incorrecto', models.TextField(blank=True, default='')),
                ('ejemplo_correcto', models.TextField(blank=True, default='')),
                ('notas', models.TextField(blank=True, default='', help_text='lo que va después del ejemplo y no es del molde')),
                ('quien_cumple', models.TextField(blank=True, default='', help_text='solo el capítulo 00')),
                ('validable', models.CharField(blank=True, choices=[('', 'Sin declarar'), ('no', 'No'), ('falta', 'Sí, falta el programa'), ('si', 'Sí, con su programa')], default='', max_length=5)),
                ('validador', models.CharField(blank=True, default='', help_text='el programa que la comprueba', max_length=200)),
                ('autoriza_escribir', models.TextField(blank=True, default='')),
                ('raya', models.BooleanField(default=False, help_text='la raya que separa la regla de su sello')),
                ('sello', models.TextField(blank=True, default='')),
                ('sello_resultado', models.CharField(blank=True, default='', max_length=10)),
                ('sello_version', models.CharField(blank=True, default='', max_length=20)),
                ('sello_fecha', models.DateField(blank=True, null=True)),
                ('sello_observacion', models.TextField(blank=True, default='')),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='estandar.capitulo')),
                ('documento', models.ForeignKey(blank=True, help_text='dónde se arma su texto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='estandar.documento')),
                ('proyecto', models.ForeignKey(blank=True, help_text='vacío: es del estándar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['capitulo__clave', 'documento__ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplica', to='estandar.regla')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estandar.tarea')),
            ],
            options={
                'ordering': ['regla', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='regla',
            name='tareas',
            field=models.ManyToManyField(blank=True, related_name='reglas', through='estandar.ReglaTarea', to='estandar.tarea'),
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('extiende', 'Extiende'), ('depende de', 'Depende de'), ('deroga', 'Deroga')], max_length=12)),
                ('codigo', models.CharField(help_text='el código de la otra regla', max_length=20)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='estandar.regla')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='estandar.regla')),
            ],
            options={
                'ordering': ['regla', 'tipo', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('regla', 'tipo', 'codigo'), name='una_dependencia_por_tipo')],
            },
        ),
        migrations.AddConstraint(
            model_name='reglatarea',
            constraint=models.UniqueConstraint(fields=('regla', 'tarea'), name='una_tarea_por_regla'),
        ),
    ]
