# Generated by Django 5.2.17 on 2026-10-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0005_reglas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['clave'], 'verbose_name': 'capítulo'},
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['regla', 'tipo', 'codigo'], 'verbose_name': 'dependencia entre reglas'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['ruta'], 'verbose_name': 'documento del estándar', 'verbose_name_plural': 'documentos del estándar'},
        ),
        migrations.AlterModelOptions(
            name='propuesta',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'propuesta'},
        ),
        migrations.AlterModelOptions(
            name='recuerdo',
            options={'ordering': ['proyecto', 'nombre'], 'verbose_name': 'recuerdo'},
        ),
        migrations.AlterModelOptions(
            name='regla',
            options={'ordering': ['capitulo__clave', 'documento__ruta', 'orden'], 'verbose_name': 'regla'},
        ),
        migrations.AlterModelOptions(
            name='reglatarea',
            options={'ordering': ['regla', 'orden'], 'verbose_name': 'tarea de una regla'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'reporte de un proyecto'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['nombre'], 'verbose_name': 'tarea'},
        ),
    ]
