# Generated by Django 5.2.17 on 2026-10-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandar', '0006_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='apartada',
            field=models.BooleanField(default=False, help_text='la regla del proyecto que salió de su texto: no se borra (20·M11)'),
        ),
        migrations.AddField(
            model_name='regla',
            name='grupo',
            field=models.CharField(blank=True, default='', help_text='la sección donde va, en las reglas de un proyecto (EP-027·HU-006)', max_length=200),
        ),
    ]
