# Generated by Django 5.2.17 on 2026-10-09 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0007_ajustes_de_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebasDelProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_parte', models.BooleanField(default=False, help_text='La pone el instalador; sin ella, el proyecto no se puede revisar.', verbose_name='tiene la parte que revisa')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name_plural': 'pruebas de los proyectos',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('herramienta', models.CharField(blank=True, help_text='Con qué se revisó: coverage.py, PHPUnit, ng test…', max_length=100)),
                ('resultado', models.CharField(choices=[('hecha', 'Hecha'), ('sin medición', 'Sin medición'), ('falló', 'Falló')], default='hecha', max_length=20)),
                ('porcentaje', models.FloatField(blank=True, help_text='Qué parte del programa tiene pruebas, de 0 a 100.', null=True)),
                ('archivos', models.JSONField(blank=True, default=list, help_text='Cada archivo con su porcentaje y sus líneas sin pruebas.')),
                ('mensaje', models.TextField(blank=True, help_text='Qué pasó, en palabras sencillas.')),
                ('navegador', models.CharField(blank=True, choices=[('pasaron', 'Pasaron'), ('fallaron', 'Fallaron'), ('sin pruebas', 'Sin pruebas de navegador')], help_text='Cómo les fue a las pruebas de navegador; vacío si no se corrieron.', max_length=20)),
                ('navegador_detalle', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'revisión de pruebas',
                'verbose_name_plural': 'revisiones de pruebas',
                'ordering': ['-fecha'],
            },
        ),
    ]
