# Generated by Django 5.2.17 on 2026-10-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebasdelproyecto',
            name='revisando_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
