# Generated by Django 5.2.17 on 2026-10-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_revisando'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebasdelproyecto',
            name='instalada_por_cimiento',
            field=models.BooleanField(default=False),
        ),
    ]
