# Generated by Django 5.2.17 on 2026-10-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_instalada_por_cimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='programa',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
