# Generated by Django 5.2.11 on 2026-08-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(db_index=True, max_length=120)),
                ('origen', models.CharField(max_length=500)),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('guardado_en', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ['proyecto', 'origen'],
                'unique_together': {('proyecto', 'origen')},
            },
        ),
    ]
