# Generated by Django 5.2.11 on 2026-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ruta', models.CharField(help_text='Carpeta raíz del proyecto en esta máquina.', max_length=500)),
                ('scope', models.CharField(blank=True, help_text='Scope de memoria, p. ej. proyecto:mi-proyecto.', max_length=120)),
                ('stack', models.CharField(blank=True, default='por detectar', help_text='Con qué está construido; «por detectar» hasta llenarse.', max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Un proyecto dado de baja no recibe avisos ni instalaciones; no se borra, para conservar su historia.')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
