# Generated by Django 5.2.17 on 2026-10-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceDeLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=500, unique=True)),
                ('posicion', models.PositiveBigIntegerField(default=0)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('modificado', models.FloatField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoDeArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('identificador', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('ruta', models.CharField(max_length=500)),
                ('caracteres', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_de_archivo', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'identificador'), name='un_gasto_por_lectura')],
            },
        ),
        migrations.CreateModel(
            name='GastoDeEnganche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('identificador', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('evento', models.CharField(blank=True, max_length=50)),
                ('caracteres', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_de_enganche', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'identificador'), name='un_gasto_por_enganche')],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('entrada', models.PositiveIntegerField(default=0)),
                ('cache_creada', models.PositiveIntegerField(default=0)),
                ('cache_leida', models.PositiveIntegerField(default=0)),
                ('salida', models.PositiveIntegerField(default=0)),
                ('auxiliar', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'mensaje'), name='una_llamada_por_mensaje')],
            },
        ),
    ]
