# Generated by Django 5.2.17 on 2026-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
        ('proyectos', '0002_proyectos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='solicitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='llamada',
            constraint=models.UniqueConstraint(fields=('sesion', 'solicitud'), name='una_llamada_por_solicitud'),
        ),
    ]
