# Generated by Django 5.2.17 on 2026-10-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0002_llamada_solicitud'),
        ('proyectos', '0002_proyectos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancedelectura',
            name='pedido',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='llamada',
            name='agente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('identificador', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('palabra', models.CharField(blank=True, max_length=40, verbose_name='palabra clave')),
                ('trabajo', models.CharField(blank=True, max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='llamada',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='consumo.pedido'),
        ),
        migrations.CreateModel(
            name='GastoDeHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('identificador', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('caracteres', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_de_herramienta', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'identificador'), name='un_gasto_por_herramienta')],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('sesion', 'identificador'), name='un_pedido_por_mensaje'),
        ),
    ]
