# Generated by Django 5.2.17 on 2026-10-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_segunda_tanda'),
        ('proyectos', '0004_tres_capas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastodeherramienta',
            name='orden',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='EjecucionDeEnganche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(db_index=True, max_length=64)),
                ('identificador', models.CharField(max_length=64)),
                ('fecha', models.DateTimeField(db_index=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('evento', models.CharField(blank=True, max_length=50)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones_de_enganche', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sesion', 'identificador'), name='una_corrida_por_identificador')],
            },
        ),
    ]
