# Generated by Django 5.2.17 on 2026-10-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0004_tercera_tanda'),
        ('proyectos', '0004_tres_capas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaDeSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=400)),
                ('huella', models.CharField(max_length=40)),
                ('posicion', models.PositiveBigIntegerField()),
                ('texto', models.TextField()),
                ('tapadas', models.PositiveIntegerField(default=0)),
                ('guardada', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_de_sesion', to='proyectos.proyecto')),
            ],
            options={
                'indexes': [models.Index(fields=['archivo', 'posicion'], name='consumo_lin_archivo_031c8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('archivo', 'huella'), name='una_linea_por_huella')],
            },
        ),
    ]
