# Generated by Django 5.2.17 on 2026-10-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0005_lineas_de_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
