# Generated by Django 5.2.11 on 2026-08-31 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_proyecto_desconectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=500)),
                ('fecha', models.CharField(max_length=10)),
                ('tema', models.CharField(blank=True, max_length=300)),
                ('huella', models.CharField(max_length=64)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha', 'archivo'],
                'unique_together': {('proyecto', 'archivo')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('quien', models.CharField(max_length=10)),
                ('cuando', models.CharField(max_length=40)),
                ('texto', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='medicion.sesion')),
            ],
            options={
                'ordering': ['sesion', 'orden'],
                'unique_together': {('sesion', 'orden')},
            },
        ),
    ]
