# Generated by Django 5.2.17 on 2026-10-06 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quien', models.CharField(help_text='cuenta, agente o el programa que lo hizo', max_length=100)),
                ('tabla', models.CharField(db_index=True, help_text='app.modelo, como proyectos.ajustedelproyecto', max_length=100)),
                ('fila', models.CharField(max_length=64)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('cambiar', 'Cambiar'), ('borrar', 'Borrar')], max_length=10)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('despues', models.JSONField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_hechos', to=settings.AUTH_USER_MODEL)),
                ('deshace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deshecho_por', to='historia.cambio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
