# Generated by Django 5.2.17 on 2026-10-06 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
        ('proyectos', '0004_tres_capas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('estandar', 'El estándar'), ('proyecto', 'Un proyecto')], max_length=10)),
                ('mayor', models.PositiveIntegerField()),
                ('menor', models.PositiveIntegerField()),
                ('parche', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('MAYOR', 'Mayor'), ('MENOR', 'Menor'), ('PARCHE', 'Parche')], max_length=6)),
                ('resumen', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('quien', models.CharField(max_length=100)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_hechas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cambio',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='historia.version'),
        ),
    ]
