# Generated by Django 5.2.11 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuando', models.CharField(max_length=40)),
                ('quien', models.CharField(max_length=100)),
                ('que_se_hizo', models.CharField(max_length=300)),
                ('sobre_que', models.CharField(max_length=300)),
                ('que_cambio', models.TextField(blank=True)),
                ('proyecto', models.CharField(blank=True, max_length=200)),
                ('sesion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['cuando'],
            },
        ),
    ]
