# Generated by Django 5.2.17 on 2026-10-05 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioDeNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=20)),
                ('anterior', models.CharField(choices=[('frena', 'Frena'), ('avisa', 'Avisa'), ('apagada', 'Apagada')], max_length=10)),
                ('nuevo', models.CharField(choices=[('frena', 'Frena'), ('avisa', 'Avisa'), ('apagada', 'Apagada')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_de_nivel', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NivelDeRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=20)),
                ('nivel', models.CharField(choices=[('frena', 'Frena'), ('avisa', 'Avisa'), ('apagada', 'Apagada')], default='frena', max_length=10)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'regla'), name='un_nivel_por_regla')],
            },
        ),
    ]
