# Generated by Django 5.2.11 on 2026-09-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(db_index=True, max_length=120)),
                ('documento', models.CharField(db_index=True, max_length=500)),
                ('quien', models.CharField(max_length=120)),
                ('cuando', models.CharField(max_length=40)),
                ('huella', models.CharField(max_length=64)),
                ('tamano', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['proyecto', 'documento', '-id'],
            },
        ),
    ]
