# Generated by Django 5.2.17 on 2026-10-05 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruta', models.CharField(help_text='La carpeta del proyecto en esta máquina.', max_length=500, unique=True)),
                ('carpeta_claude', models.CharField(editable=False, help_text='Dentro de ~/.claude/projects/; se calcula desde la ruta.', max_length=500, verbose_name='carpeta de Claude Code')),
                ('limite_enganche', models.PositiveIntegerField(default=2000, help_text='Tokens que puede agregar un enganche antes de avisar.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='límite por enganche')),
                ('limite_archivo', models.PositiveIntegerField(default=10000, help_text='Tokens que puede ocupar un archivo leído antes de avisar.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='límite por archivo')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
