# Generated by Django 5.2.17 on 2026-10-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectos_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPrendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion', models.CharField(help_text='La transcripción de la sesión, relativa al proyecto.', max_length=255)),
                ('analisis', models.CharField(help_text='El análisis, relativo al proyecto.', max_length=500)),
                ('desde', models.PositiveIntegerField(help_text='El primer turno que entra.')),
                ('pausa', models.PositiveIntegerField(blank=True, help_text='Desde qué turno está en pausa.', null=True)),
                ('pausas', models.CharField(blank=True, default='', help_text='Los tramos ya pausados: 3-5,9-9.', max_length=500)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_prendidos', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'sesion'), name='un_analisis_por_sesion')],
            },
        ),
    ]
