# Generated by Django 5.2.17 on 2026-10-05 22:15
"""`EP-025·HU-013` · La configuración en tres capas.

Los límites de cada proyecto pasan de sus columnas a sus ajustes antes de
quitar las columnas; solo los que no son el de fábrica, porque el de fábrica ya
vale sin fila. La reversa los devuelve (`03·D2`).
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FABRICA = {"limite_enganche": 2000, "limite_archivo": 10000}


def pasar_a_ajustes(apps, schema_editor):
    Proyecto = apps.get_model("proyectos", "Proyecto")
    AjusteDelProyecto = apps.get_model("proyectos", "AjusteDelProyecto")
    for proyecto in Proyecto.objects.all():
        for clave, fabrica in FABRICA.items():
            valor = getattr(proyecto, clave)
            if valor and valor != fabrica:
                AjusteDelProyecto.objects.update_or_create(proyecto_id=proyecto.pk, clave=clave,
                                                           defaults={"valor": str(valor)})


def devolver_a_columnas(apps, schema_editor):
    Proyecto = apps.get_model("proyectos", "Proyecto")
    AjusteDelProyecto = apps.get_model("proyectos", "AjusteDelProyecto")
    for ajuste in AjusteDelProyecto.objects.filter(clave__in=list(FABRICA)):
        Proyecto.objects.filter(pk=ajuste.proyecto_id).update(**{ajuste.clave: int(ajuste.valor)})


CLAVES = [('rutas_en_avisos', 'Rutas en los avisos'), ('limite_enganche', 'Límite por enganche'),
          ('limite_archivo', 'Límite por archivo')]


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_analisisprendido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=CLAVES, max_length=50, unique=True)),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('regla', 'Una regla'), ('enganche', 'El freno entero')], max_length=10)),
                ('nombre', models.CharField(help_text='El ID de la regla, o «freno».', max_length=30)),
                ('motivo', models.CharField(max_length=500)),
                ('vence', models.DateTimeField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('levantada', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('levantada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensiones_levantadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-creada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AjusteDelProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=CLAVES, max_length=50)),
                ('valor', models.CharField(max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_propios', to='proyectos.proyecto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'clave'), name='un_valor_por_ajuste')],
            },
        ),
        migrations.RunPython(pasar_a_ajustes, devolver_a_columnas),
        migrations.RemoveField(
            model_name='proyecto',
            name='limite_archivo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='limite_enganche',
        ),
    ]
