# Generated by Django 5.2.17 on 2026-10-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_sin_opt_in_17'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustebase',
            name='clave',
            field=models.CharField(choices=[('rutas_en_avisos', 'Rutas en los avisos'), ('limite_enganche', 'Límite por enganche'), ('limite_archivo', 'Límite por archivo'), ('revision_pruebas', 'Revisión de pruebas: qué tan estricto ser'), ('dias_revision', 'Revisión de pruebas: cada cuántos días'), ('opt_in_15', 'Patrón opt-in 15 (registros inmutables)'), ('opt_in_16', 'Patrón opt-in 16 (cumplimiento normativo)'), ('opt_in_18', 'Patrón opt-in 18 (despliegue e infraestructura)'), ('opt_in_19', 'Patrón opt-in 19 (observabilidad y operación)'), ('opt_in_21', 'Patrón opt-in 21 (automatización de procesos)'), ('opt_in_22', 'Patrón opt-in 22 (sistemas que aprenden de datos)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ajustedelproyecto',
            name='clave',
            field=models.CharField(choices=[('rutas_en_avisos', 'Rutas en los avisos'), ('limite_enganche', 'Límite por enganche'), ('limite_archivo', 'Límite por archivo'), ('revision_pruebas', 'Revisión de pruebas: qué tan estricto ser'), ('dias_revision', 'Revisión de pruebas: cada cuántos días'), ('opt_in_15', 'Patrón opt-in 15 (registros inmutables)'), ('opt_in_16', 'Patrón opt-in 16 (cumplimiento normativo)'), ('opt_in_18', 'Patrón opt-in 18 (despliegue e infraestructura)'), ('opt_in_19', 'Patrón opt-in 19 (observabilidad y operación)'), ('opt_in_21', 'Patrón opt-in 21 (automatización de procesos)'), ('opt_in_22', 'Patrón opt-in 22 (sistemas que aprenden de datos)')], max_length=50),
        ),
    ]
