# Generated by Django 5.2.11 on 2026-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ruta_codigo', models.CharField(max_length=500)),
                ('ruta_normalizada', models.CharField(db_index=True, max_length=500)),
                ('version_reglas', models.CharField(blank=True, max_length=40)),
                ('conectado', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
