# Generated by Django 5.2.11 on 2026-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='desconectado',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
