# Generated by Django 5.2.11 on 2026-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_desconectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_el_estandar',
            field=models.BooleanField(default=False, help_text='Marcar solo en el repositorio del estándar. A ese no se le reclama qué versión sigue: la versión que es está en su archivo VERSION.', verbose_name='Es el estándar mismo'),
        ),
    ]
